name: the_open_quran
description: The Holy Qur'an App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Localications
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  #State Managements
  provider: ^6.0.3                                        # Provide state management
  rxdart: ^0.27.7

  #Network
  http: ^0.13.5
  html: ^0.15.1


  # Google
  google_fonts: ^3.0.1                                    # Text fonts

  # Widgets
  cupertino_icons: ^1.0.2                                 # Cupertino icons
  flutter_svg: ^1.1.5                                     # Reading SVG images
  auto_size_text: ^3.0.0
  custom_sliding_segmented_control: ^1.7.2
  syncfusion_flutter_sliders: ^20.3.52
  scrollable_positioned_list: ^0.3.5
  gap: ^2.0.0                                             # Adding gaps between widgets
  flutter_slidable: ^2.0.0                                # Slidable list item
  audio_video_progress_bar: ^1.0.0

  # Local Database
  get_storage: ^2.0.3                                     # Store data locally

  #Helpers
  flutter_native_splash: ^2.2.10+1                        # Native Splash
  package_info_plus: ^2.0.0
  path_provider: ^2.0.11
  equatable: ^2.0.5
  html_character_entities: ^1.0.0+1
  share_plus: ^6.3.0
  in_app_review: ^2.0.6
  flutter_launcher_icons: ^0.11.0
  url_launcher: ^6.1.10
  modal_bottom_sheet: ^3.0.0-pre
  dartarabic: ^0.1.2


  #Audio
  just_audio: ^0.9.30
  audio_service: ^0.18.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_icons:
  image_path_ios: 'assets/icons/ic_launch.png'
  image_path_android: 'assets/icons/ic_launch.png'
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/json/translations/


  fonts:
    - family: UthmaniIcon
      fonts:
        - asset: assets/fonts/UthmanicRegular.ttf
    - family: Uthmani
      fonts:
        - asset: assets/fonts/UthmanTN_v2-0.ttf
    - family: Uthmanic Bold
      fonts:
        - asset: assets/fonts/UthmanicBold.ttf
    - family: Majeed
      fonts:
        - asset: assets/fonts/AlMajeed.ttf
    - family: Me
      fonts:
        - asset: assets/fonts/Me.ttf
    - family: Jameel
      fonts:
        - asset: assets/fonts/Jameel.ttf
    - family: Kufam Regular
      fonts:
        - asset: assets/fonts/KufamRegular.ttf
    - family: Noore
      fonts:
        - asset: assets/fonts/Noore.ttf
    - family: Naskh
      fonts:
        - asset: assets/fonts/Naskh.ttf
    - family: Quran Font
      fonts:
        - asset: assets/fonts/QuranFont.ttf
    